name: Echo Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to checkout"
        required: true
        default: "master"

jobs:
  echo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - run: |
          ls -a
          echo ""
          git branch -a